### ISSUE TITLE
Open Source Licence

### ISSUE THREAD

**Issue by LeeBergstrand** [beatrizgj/MDPbiome#1]
Hello!

I am very interested in this work! Congrats on the publication! I noticed that this software is not currently open source licenced. Are there any plans to add an open source licence to this repository? An Apache V2 licence would be preferred. https://www.apache.org/licenses/LICENSE-2.0.html

Cheers!

**Comment by beatrizgj** [comment]
Hi Lee!
Thanks for your interest in our system!
You are right, about the not open source license for MDPbiome software. Sorry for the inconveniences. We are selecting it, and it will be open source licensed in the next days.

Cheers

**Comment by beatrizgj** [comment]
MIT license added!
